driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/omnibus-atools']

provisioner:
  name: shell
  script: build.sh

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
