#!/bin/bash
#
# Perform necessary atools setup steps
# after package is installed.
#
set -e

PROGNAME=$(basename $0)
INSTALLER_DIR=/opt/atools/embedded/bin
PREFIX="/usr/local/bin"
WHICHPATH="/usr/local/bin/whichversion"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

binaries="kitchen kitchen-ansible-inventory aeco ansible ansible-doc ansible-galaxy ansible-playbook ansible-vault atools"

# rm -f before ln -sf is required for solaris 9
for binary in $binaries; do
  echo "Trying to rm $PREFIX/$binary"
  rm -f $PREFIX/$binary || error_exit "Cannot remove $PREFIX/$binary"

  echo "Trying to ln -sf $WHICHPATH $PREFIX/$binary"
  ln -sf $WHICHPATH $PREFIX/$binary || error_exit "Cannot link $WHICHPATH to $PREFIX/$binary"
done


chown -Rh 0:0 $INSTALLER_DIR

echo "Thank you for installing atools!"

exit 0
